kind: Service
apiVersion: v1
metadata:
  name: glogger-audit-nodeport-service
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"web-port":"HTTPS"}' 
  labels:
    name: glogger-audit-web-deployment
    type_component: webapp
    language: javascript
    owner: is_global_regional_application
    managed-by: jenkins
    environment: testing
    region: global    
spec:
   # [START SELECTOR] 
  selector:
    name: glogger-audit-web-deployment
    environment: testing    
   # [END SELECTOR] 
  type: NodePort
  ports:
  - name: web-port
    port: 443
    targetPort: 443